--
- hosts: all
  become: yes
  tasks:
  - name: update
    apt: update_cache=yes
  
  - name: Install pip
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items:
    - python-pip
    - python3-pip
    become: true


--
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      package: "name=python3-pip state=latest"
  

