---
- hosts: all
  become: yes
  tasks:
    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
    
    - name: Restart gunicorn socket
      service:
        name: gunicorn.socket
        state: restarted
    
    - name: Restart gunicorn service
      service:
        name: gunicorn.service
        state: restarted
